macro(set_output_dir dir)
	foreach(c ${CMAKE_CONFIGURATION_TYPES})
		string(TOUPPER ${c} c )
		set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_${c} ${dir})
		set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_${c} ${dir})
		set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_${c} ${dir})
	endforeach()
endmacro()

function(add_static_lib name source_list folder)
	add_library(${name} STATIC ${source_list})
	set_target_properties(${name} PROPERTIES FOLDER ${folder})
endfunction()

function(add_lib name source_list folder)
	add_library(${name} SHARED ${source_list})
	set_target_properties(${name} PROPERTIES FOLDER ${folder})
endfunction()

function(add_exe name source_list folder)
	add_executable(${name} ${source_list})
	set_target_properties(${name} PROPERTIES FOLDER ${folder})
	set_target_properties(${name} PROPERTIES VS_DEBUGGER_WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}/bin")
endfunction()

