local root_event_receiver = root:get_component_n("cEventReceiver")
make_obj(root_event_receiver, "cEventReceiver")
root_event_receiver:add_mouse_click_listener_s(get_slot(
	function()
		local e = flame_call(nil, find_udt("Entity")["create"])
		e:load("assets/ball")
		local node = e:get_component_n("cNode")
		make_obj(node, "cNode")
		node:set_pos(camera.pos)
		local rigid = e:get_component_n("cRigid")
		make_obj(rigid, "cRigid")
		rigid:add_impulse({x=-camera.dir1.x*5, y=-camera.dir1.y*5, z=-camera.dir1.z*5})
		node:set_pos(camera.pos)
		root:add_child(e.p)
	end
))
